### PR TITLE
Added decodeRctSimple

### PR DESCRIPTION
**Pull request by gutenye**

### CODE REVIEW

**Comment by paulshapiro** [comment]
@gutenye hey there, could I trouble you to rebase?

**Comment by paulshapiro** [comment]
@gutenye I won't be able to include these functions in core-js anymore if we don't get to rebase these.

**Comment by gutenye** [comment]
@paulshapiro Sorry, forgot these 2 PRs. Doing it now.

**Comment by paulshapiro** [comment]
Awesome!!

**Comment by gutenye** [comment]
Rebased.

**Comment by paulshapiro** [comment]
Yesssss

**Comment by paulshapiro** [comment]
So @gutenye I'm actually getting a test failure on this one.

1: [2018-12-12T…:00Z | 0x110bc75c0 | rctSigs.cpp line 1097]: decodeRct called on non-full rctSig
1: bridged__decodeRctSimple: mask_string: 809e62e6fe7f000003c55d0901000000f89e62e6fe7f0000f89e62e6fe7f0000
1: […]/mymonero-core-cpp/test/test_all.cpp:1244: fatal error: in "bridged__decodeRctSimple": critical check mask_string == "51bdfc13c6757758148dd493a77e94073a062622a056a915a457abe6ca6c050b" has failed

**Comment by gutenye** [comment]
Let me build and test it. I ran tests in `mymonero-core-js.src/tests/MyMoneroCoreCpp.node.js` (I haven't figured out how to run c++ tests) :(

**Comment by paulshapiro** [comment]
You can just go `bin/buildAndRun_tests`

**Comment by gutenye** [comment]
I got an error:

```
[N]  ❯ bin/buildAndRun_tests
CMake Warning at /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake:125 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:6 (project)


-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   thread
--   chrono
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/src/submodules/mymonero-core-cpp/build
[  1%] Building CXX object CMakeFiles/test_all.dir/test/test_all.cpp.o
In file included from /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/src/submodules/mymonero-core-cpp/test/test_all.cpp:37:
In file included from /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/contrib/boost-sdk/boost/test/unit_test.hpp:18:
In file included from /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/contrib/boost-sdk/boost/test/test_tools.hpp:17:
In file included from /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/contrib/boost-sdk/boost/config.hpp:57:
In file included from /Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/contrib/boost-sdk/boost/config/platform/macos.hpp:28:
/Users/guten/data/dev/study/blockchain/monero/mymonero-core-js.src/contrib/boost-sdk/boost/config/detail/posix_features.hpp:18:15: fatal error:
      'unistd.h' file not found
#     include <unistd.h>
              ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/test_all.dir/test/test_all.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_all.dir/all] Error 2
make: *** [all] Error 2
```

A quick Google search says I don't have `/usr/include/unistd.h` file

**Comment by paulshapiro** [comment]
You appear to be in core-js rather than core-cpp.

**Comment by paulshapiro** [comment]
Do you have the xcode command line tools installed?

**Comment by gutenye** [comment]
I have installed the xcode command line tools.

The problem is gcc shows `MacOSX10.14.sdk`, but `cmake` in `bin/buildAndRun_tests` shows `MacOSX10.13.sdk directory not exists`. I installed cmake via homebrew, does it cause the problem? 

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by paulshapiro** [comment]
I also use brew for cmake, so I don't believe so. Perhaps you need to do a `brew update`, `brew upgrade`, `brew doctor`, etc?

**Comment by gutenye** [comment]
Fixed it by symlink from `MacOSX10.14.sdk` to `MacOSX10.13.sdk`. Running tests now.

**Comment by gutenye** [comment]
@paulshapiro Thanks for the help. Fixed, a PR will be sent shortly.

**Comment by paulshapiro** [comment]
Anytime

**Pull request merged**
