### PR TITLE
Added derivation_to_scalar

### PR DESCRIPTION
**Pull request by gutenye**

### CODE REVIEW

**Comment by paulshapiro** [comment]
Awesome. Looks good to me. Thanks for doing this! Does it affect anything on your side if I wait on some other changes before merging your PR?

**Comment by paulshapiro** [comment]
Hm we should add an AUTHORS file..

**Comment by paulshapiro** [comment]
@gutenye could I trouble you to rebase this one too?

**Comment by gutenye** [comment]
rebased

**Comment by paulshapiro** [comment]
👍

**Pull request merged**
