### PR TITLE
Added estimate_rct_tx_size

### PR DESCRIPTION
**Pull request by gutenye**

### CODE REVIEW

**Comment by paulshapiro** [comment]
I'd actually removed this function after we moved the fee finding / tx construction attempt implementation to this repo. What do you use this function for in JS?

**Comment by gutenye** [comment]
In [Exodus](https://www.exodus.io/), we don't use the all-in-one function `monero_sendingFunds_utils.SendFunds`, everything is handled in lower-level, download the whole blockchain data, finding transactions and utxos locally and store them, build transactions from them and broadcast it.

In the send dialog, the fee is calculated according to the amount (utxos) you input in realtime. 

screen shot 2018-11-23 at 9 20 14 am

If it's removed, how does fee calculation work in MyMonero?

**Comment by paulshapiro** [comment]
Gotcha, makes sense, yeah you mentioned you work with the RPC result directly. In MyMonero, we display an estimate of the fee with `estimated_tx_network_fee`, but the actual fee is calculated within step2 of the "decomposed" Send procedure in `monero_transfer_utils`. 

Ideally this code will continue to converge with Monero mainline's create_transactions_2 / transfer_selected* implementation - they both call into the same cryptonote_tx_utils after all. I think it will become simpler/clearer as MyMonero implements the block-streaming hybrid mode, since data structures should be unified there.

**Comment by paulshapiro** [comment]
@gutenye As mentioned, serial_bridge is missing the functions you added - totally my fault for not checking.

Here is the commit and line where I removed estimate_rct_tx_size so you have a reference:

https://github.com/mymonero/mymonero-core-cpp/compare/4ae115f8427621b96c8e12fac8ac90c7b2a39ea2...ee3eede5d20668c720c2fb86fd163f4ec0bfee9b#diff-07b294142939496fff575ac6baa56c0aL382

**Comment by paulshapiro** [comment]
What the heck, that link suddenly does not work. One sec

**Comment by paulshapiro** [comment]
https://github.com/mymonero/mymonero-core-cpp/compare/4ae115f8427621b96c8e12fac8ac90c7b2a39ea2...ee3eede5d20668c720c2fb86fd163f4ec0bfee9b#diff-07b294142939496fff575ac6baa56c0aL383

**Comment by paulshapiro** [comment]
What the heck. It works when I paste it into browser. I think github is editing the link

**Comment by paulshapiro** [comment]
> https://github.com/mymonero/mymonero-core-cpp/compare/4ae115f8427621b96c8e12fac8ac90c7b2a39ea2...ee3eede5d20668c720c2fb86fd163f4ec0bfee9b#diff-07b294142939496fff575ac6baa56c0aL383

**Comment by paulshapiro** [comment]
`https://github.com/mymonero/mymonero-core-cpp/compare/4ae115f8427621b96c8e12fac8ac90c7b2a39ea2...ee3eede5d20668c720c2fb86fd163f4ec0bfee9b#diff-07b294142939496fff575ac6baa56c0aL383`

**Comment by paulshapiro** [comment]
There we go. So you see, fairly straightforward.

**Comment by gutenye** [comment]
I don't follow, what is missing? I saw [serial_bridge::estimate_rct_tx_size](https://github.com/mymonero/mymonero-core-cpp/blob/develop/src/serial_bridge_index.cpp#L330) is in the develop branch.

From my understanding, actual fee is calculated in step2, if actual fee is larger than the estimated fee, retry step1. Can we use the estimated fee from step1 directly? Or Does monero enforce to calculate the fee must after tx is built?

**Comment by paulshapiro** [comment]
Oh crap, you are completely right! Silly mistake on my part. Thanks Guten.

**Comment by paulshapiro** [comment]
(Reason I made the mistake was I looked at the PR's diff and also hadn't seen it in there either)

**Comment by gutenye** [comment]
Not a problem. Mistake happens all the time. :)

**Pull request merged**
